[build]
  functions = "functions"
[[redirects]]
from = "/api/{target-host}/{target-path}"
to = "/{target-host}/{target-path}"
status = 200

[[functions]]
path = "/{target-host}/{target-path}"
script = "functions/proxy.js"
